This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./ZHAW_SYSARCH_SEM_HA.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ZHAW_SYSARCH_SEM_HA.acn....done (152 entries accepted, 0 rejected).
Sorting entries....done (1216 comparisons).
Generating output file ZHAW_SYSARCH_SEM_HA.acr....done (66 lines written, 0 warnings).
Output written in ZHAW_SYSARCH_SEM_HA.acr.
Transcript written in ZHAW_SYSARCH_SEM_HA.alg.
