This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./ZHAW_SM_ComputerForensik_Daniel_Brun.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ZHAW_SM_ComputerForensik_Daniel_Brun.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (24 comparisons).
Generating output file ZHAW_SM_ComputerForensik_Daniel_Brun.acr....done (12 lines written, 0 warnings).
Output written in ZHAW_SM_ComputerForensik_Daniel_Brun.acr.
Transcript written in ZHAW_SM_ComputerForensik_Daniel_Brun.alg.
